### ISSUE TITLE
Server produces incomplete connection initiation message.

### ISSUE THREAD

**Issue by alex-konovalov** [OpenMath/py-scscp#4]
@defeo I was told by @Sebasguts about this - please see https://github.com/gap-packages/scscp/issues/9. 

Indeed, page 11 of SCSCP 1.3 specification says:
> "The format of the control sequence is compulsory, and server implementations must not change the order of the attribute/value pairs nor omit some of them. This strict
restriction makes it sure that even very simple clients should be able to parse this
control sequence." 

However, Python SCSCP server produces incomplete connection initiation message: with `SetInfoLevel(InfoSCSCP,4)` in GAP, I can see that:

```
gap> GetServiceDescription("localhost",26133);
#I  Creating a socket ...
#I  Connecting to a remote socket via TCP/IP ...
#I  Got connection initiation message
#I  <?scscp scscp_versions="1.3" ?>
```

An example of a properly formatted connection initiation message returned by a GAP SCSCP server:
```
gap> GetServiceDescription("localhost",26134);
#I  Creating a socket ...
#I  Connecting to a remote socket via TCP/IP ...
#I  Got connection initiation message
#I  <?scscp service_name="GAP" service_version="4.8.6" service_id="localhost:26134:65854" scscp_versions="1.0 1.1 1.2 1.3" ?>
```

**Comment by defeo** [comment]
Thanks, it's fixed.

But why oh why preserve attribute order? This makes the thing more painful, not easier to implement!

**Comment by alex-konovalov** [comment]
Thanks. Maybe we may relax this in the next version of SCSCP - please submit an issue to https://github.com/alex-konovalov/scscp
